### ISSUE TITLE
Document issues with vue-slick-carousel

### ISSUE THREAD

**Issue by weotch** [BKWLD/vue-carousel#1]
Based on pain points we're experiencing with vue-slick-carousel, I think, ultimately, we want to build our own carousel.  Can you update the README with some of the issues you've encountered so far that required workarounds?

- [x] @jonjahr adds notes
- [x] @isaazgarcia adds notes

**Comment by jonjahr** [comment]
@weotch I've added vue-slick-carousel pain points to the readme.  Great timing, I was just dealing with this last night and on Friday.

**Comment by weotch** [comment]
Nice, yah, wanted to grab your impressions while it was fresh.

**Comment by isaazgarcia** [comment]
I added my thoughts. One thing to note is that this implementation of vue-slick-carousel is not as complete as the original slick carousel, like there are some css classes and functions that are missing or aren't getting fired.

**Comment by weotch** [comment]
Thanks guys!
